### ISSUE TITLE
broken link on https://open.edx.org/blog/newest-open-edx-release-dogwood-now-available

### ISSUE THREAD

**Issue by yarikoptic** [openedx-unsupported/edx-documentation#1200]
Probably not correct repository but failed to find if blogs are within git anywhere

on
https://open.edx.org/blog/newest-open-edx-release-dogwood-now-available
Installation Guide points to http://edx.readthedocs.org/projects/open-edx-icr/en/named-release-dogwood.rc/   which is non-existent

**Comment by nedbat** [comment]
Thanks, the blog is not on GitHub, but we'll fix the link.

**Comment by lamagnifica** [comment]
@yarikoptic thank you for the catch! The open.edx.org site is updated separately, and isn't hosted on GitHub. I hope you are now exploring the new Eucalyptus release though. See https://open.edx.org/blog/eucalyptus-new-release-chew

@jbarciauskas I don't have permission to edit the referenced blog post.
I suggest changing the sentence to sned people to the release notes instead of the installation instructions. 
http://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/dogwood.html

**Comment by nedbat** [comment]
I've fixed the link in the blog post, thanks!

**Comment by Adamalshihabi** [comment]
broken link : 
https://developers.google.com/webmasters/state-of-the-web/2005/classes?csw=1

**Comment by nedbat** [comment]
@Adamalshihabi we don't know where you found that link.  Please open new issues with complete details.  Thanks.
